version: '3.9'

services:
  postgres:
    image: postgres:16.3-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    container_name: nestjs-template-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data  
      - ./data/:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nestjs-template-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@test.com
      - PGADMIN_DEFAULT_PASSWORD=test
    ports:
      - '5050:80'
    depends_on:
      - postgres

volumes:
  postgres-data: